[package]
name = "get-permutations"
version = "0.1.0"
edition = "2018"

[dependencies]


[profile.release]
opt-level = 3
debug = true
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = 'unwind'
incremental = false
codegen-units = 1
rpath = false
